[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
sysinfo = "*"

[build-dependencies]
tonic-build = "*"
