[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
sysinfo = "*"
uuid = { version = "1.17.0", features = ["v4"] }

[build-dependencies]
tonic-build = "*"
